ALTER TABLE `person` ADD `deleted` TINYINT(1) NOT NULL DEFAULT '0';
ALTER TABLE `company` ADD `deleted` TINYINT(1) NOT NULL DEFAULT '0';
ALTER TABLE `note` ADD `deleted` TINYINT(1) NOT NULL DEFAULT '0';