<!-- 
/**
 * TDProject_ERP
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */
-->
<?php

$request = $this->getRequest();

$dto = $this->getRequest()->getAttribute(
    TDProject_Core_Controller_Util_WebRequestKeys::VIEW_DATA
);

?>

<script language="JavaScript" src="www/design/core/templates/global/js/jquery.dataTables.js"></script>
<script type="text/javascript" charset="utf-8">
$(document).ready(function() {
	$('#personGrid').dataTable( {
		"bJQueryUI": true,
		"sPaginationType": "full_numbers"
	} );
} );
</script>

<h2>Personen</h2>
<form method="post" name="personNoteForm" class="yform" id="personNoteForm">
	<input type="hidden" name="path" value="<?php echo $request->getParameter(TechDivision_Controller_Action_Controller::ACTION_PATH) ?>"/>
	<input type="hidden" name="method" value="savePersonNotes"/>
	<input type="hidden" name="noteId" value="<?php echo $dto->getNoteId() ?>"/>
	<fieldset class="ui-widget ui-widget-content ui-corner-all">
    	<legend>Personen zuordnen</legend>
    	<div id="dynamic">
    		<table cellpadding="0" cellspacing="0" border="0" class="display" id="personGrid">
    			<thead>
        			<tr>
                        <th width="5%"></th>
                        <th width="10%">Id</th>
                        <th width="25%">Name</th>
                        <th width="25%">Telefon</th>
                        <th width="20%">Grund</th>
                        <th width="15%">Aktion</th>       
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($dto->getPersons() as $person) { ?><tr>
                        <td><input value="<?php echo $person->getPersonId() ?>" name="persons[]" type="checkbox"<?php if ($this->isPerson($person)) { ?> checked='checked'<?php } ?>/></td>
                        <td><?php echo $person->getPersonId() ?></td>
                        <td><?php echo $person->getLastname() ?>, <?php echo $person->getFirstname() ?></td>
                        <td><?php echo $person->getPhone() ?></td>
                        <td>
                            <input name="reasons[<?php echo $person->getPersonId() ?>]" id="reasons" type="text" value="<?php echo $this->getPersonReason($person) ?>"/>
                        </td>
                        <td><a href="<?php echo "?path=/person&method=edit&personId=" . $person->getPersonId()?>">Bearbeiten</a></td>
                    </tr><?php } ?>
                </tbody>
    			<tfoot>
        			<tr>
                        <th></th>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Telefon</th>
                        <th>Grund</th>
                        <th>Aktion</th>       
                    </tr>
                </tfoot>                   
            </table>
        </div>
    </fieldset>
    <fieldset class="ui-widget ui-widget-content ui-corner-all">
    	<legend>Aktionen</legend>
        <div class="type-button">
            <input type="submit" id="submit" value="Speichern"/>
        </div> 
    </fieldset>   
</form>